@{
    # Module manifest for MDEValidator
    # Generated by: MDEValidator Team

    # Version number of this module
    ModuleVersion = '1.1.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID = 'e8f9c7d6-5a4b-3c2d-1e0f-9a8b7c6d5e4f'

    # Author of this module
    Author = 'Nathan Hutchinson'

    # Company or vendor of this module
    CompanyName = 'Nathan Hutchinson'

    # Copyright statement for this module
    Copyright = '(c) 2026 Nathan Hutchinson. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'PowerShell module to validate Microsoft Defender for Endpoint (MDE) configurations and security settings.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Script module or binary module file associated with this manifest
    RootModule = 'MDEValidator.psm1'

    # Functions to export from this module
    FunctionsToExport = @(
        'Test-MDEConfiguration',
        'Get-MDEValidationReport',
        'Get-MDEOperatingSystemInfo',
        'Get-MDESecuritySettingsManagementStatus',
        'Get-MDEOnboardingStatusString',
        'Get-MDEManagementType',
        'Get-MDEManagedDefenderProductType',
        'Get-MDEManagementTypeFallback',
        'Get-MDEPolicyRegistryPath',
        'Get-MDEPolicySettingConfig',
        'Test-MDEPolicyRegistryValue',
        'Test-MDEPolicyRegistryVerification',
        'Test-MDEServiceStatus',
        'Test-MDEPassiveMode',
        'Test-MDEAntiSpywareEnabled',
        'Test-MDEIoavProtectionEnabled',
        'Test-MDENISEnabled',
        'Test-MDESignatureAge',
        'Test-MDESignatureInfo',
        'Test-MDERealTimeProtection',
        'Test-MDECloudProtection',
        'Test-MDECloudBlockLevel',
        'Test-MDECloudExtendedTimeout',
        'Test-MDESampleSubmission',
        'Test-MDEBehaviorMonitoring',
        'Test-MDEOnboardingStatus',
        'Test-MDEDeviceTags',
        'Test-MDENetworkProtection',
        'Test-MDENetworkProtectionWindowsServer',
        'Test-MDEDatagramProcessingWindowsServer',
        'Test-MDEAutoExclusionsWindowsServer',
        'Test-MDEAttackSurfaceReduction',
        'Test-MDEThreatDefaultActions',
        'Test-MDETroubleshootingMode',
        'Test-MDETamperProtection',
        'Test-MDETamperProtectionForExclusions',
        'Test-MDEExclusionVisibilityLocalAdmins',
        'Test-MDEExclusionVisibilityLocalUsers',
        'Test-MDESmartScreen',
        'Test-MDESmartScreenPUA',
        'Test-MDESmartScreenPromptOverride',
        'Test-MDESmartScreenDownloadOverride',
        'Test-MDESmartScreenDomainExclusions',
        'Test-MDESmartScreenAppRepExclusions',
        'Test-MDEDisableCatchupQuickScan',
        'Test-MDERealTimeScanDirection',
        'Test-MDESignatureUpdateFallbackOrder',
        'Test-MDESignatureUpdateInterval',
        'Test-MDEDisableLocalAdminMerge',
        'Test-MDEFileHashComputation',
        'Test-MDEPUAProtection'
    )

    # Cmdlets to export from this module
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData = @{
        PSData = @{
            # Tags applied to this module
            Tags = @('Security', 'Defender', 'MDE', 'Endpoint', 'Validation', 'Windows')

            # A URL to the license for this module
            LicenseUri = 'https://github.com/NateHutch365/MDEValidator/blob/main/LICENSE'

            # A URL to the main website for this project
            ProjectUri = 'https://github.com/NateHutch365/MDEValidator'

            # ReleaseNotes of this module
            ReleaseNotes = 'v1.1.0 — Onboarding & Device State Expansion

New checks added to Test-MDEOnboardingStatus:
- DiagTrack (Connected User Experiences and Telemetry) service status — Warning if absent or stopped
- OrgId registry value (HKLM:\SOFTWARE\Microsoft\Windows Advanced Threat Protection\Status) — Info when present, Warning when absent
- WDATPOnboarding event log query — surfaces event count and latest timestamp; Warning if no events found

New device state functions:
- Test-MDEAntiSpywareEnabled — Pass when enabled, Warning when disabled
- Test-MDEIoavProtectionEnabled — Pass when enabled, Warning when disabled
- Test-MDENISEnabled — Pass when enabled, Warning when disabled
- Test-MDESignatureAge — Pass (0-1 days), Warning (2-3 days), Fail (>3 days) for both AV and AS signatures
- Test-MDESignatureInfo — Informational AV signature version and last updated date

Extended existing functions:
- Test-MDEPassiveMode now also surfaces AMRunningMode — Pass when Normal, Warning otherwise

Bug fixes:
- Null guards added to Test-MDESignatureAge preventing silent false-positives when WMI returns null signature age
- Null guard added to Test-MDESignatureInfo preventing empty version string when WMI returns null

Total: 377 Pester tests (0 failures), zero PSScriptAnalyzer violations'
        }
    }
}
