@{
    # Module manifest for MDEValidator
    # Generated by: MDEValidator Team

    # Version number of this module
    ModuleVersion = '1.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID = 'e8f9c7d6-5a4b-3c2d-1e0f-9a8b7c6d5e4f'

    # Author of this module
    Author = 'MDEValidator Team'

    # Company or vendor of this module
    CompanyName = 'Community'

    # Copyright statement for this module
    Copyright = '(c) 2024 MDEValidator Team. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'PowerShell module to validate Microsoft Defender for Endpoint (MDE) configurations and security settings.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Script module or binary module file associated with this manifest
    RootModule = 'MDEValidator.psm1'

    # Functions to export from this module
    FunctionsToExport = @(
        'Test-MDEConfiguration',
        'Get-MDEValidationReport',
        'Get-MDEOperatingSystemInfo',
        'Get-MDESecuritySettingsManagementStatus',
        'Get-MDEManagementType',
        'Get-MDEManagedDefenderProductType',
        'Get-MDEManagementTypeFallback',
        'Get-MDEPolicyRegistryPath',
        'Get-MDEPolicySettingConfig',
        'Test-MDEPolicyRegistryValue',
        'Test-MDEPolicyRegistryVerification',
        'Test-MDEServiceStatus',
        'Test-MDEPassiveMode',
        'Test-MDERealTimeProtection',
        'Test-MDECloudProtection',
        'Test-MDECloudBlockLevel',
        'Test-MDECloudExtendedTimeout',
        'Test-MDESampleSubmission',
        'Test-MDEBehaviorMonitoring',
        'Test-MDEOnboardingStatus',
        'Test-MDENetworkProtection',
        'Test-MDENetworkProtectionWindowsServer',
        'Test-MDEDatagramProcessingWindowsServer',
        'Test-MDEAttackSurfaceReduction',
        'Test-MDEThreatDefaultActions',
        'Test-MDETamperProtection',
        'Test-MDETamperProtectionForExclusions',
        'Test-MDEExclusionVisibilityLocalAdmins',
        'Test-MDEExclusionVisibilityLocalUsers',
        'Test-MDESmartScreen',
        'Test-MDESmartScreenPUA',
        'Test-MDESmartScreenPromptOverride',
        'Test-MDESmartScreenDownloadOverride',
        'Test-MDESmartScreenDomainExclusions',
        'Test-MDESmartScreenAppRepExclusions',
        'Test-MDEDisableCatchupQuickScan',
        'Test-MDERealTimeScanDirection',
        'Test-MDESignatureUpdateFallbackOrder',
        'Test-MDESignatureUpdateInterval',
        'Test-MDEDisableLocalAdminMerge',
        'Test-MDEFileHashComputation'
    )

    # Cmdlets to export from this module
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData = @{
        PSData = @{
            # Tags applied to this module
            Tags = @('Security', 'Defender', 'MDE', 'Endpoint', 'Validation', 'Windows')

            # A URL to the license for this module
            LicenseUri = ''

            # A URL to the main website for this project
            ProjectUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = 'Initial release of MDEValidator module.'
        }
    }
}
